// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import ui "github.com/themartian0x48/ui/go"

func SelectDemo() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"doc-section\"><header class=\"doc-section__header\"><h1 class=\"doc-section__title\">Select</h1><p class=\"doc-section__description\">A component that allows users to pick a single option from a dropdown list.</p></header><div class=\"doc-demo\"><div class=\"doc-demo__preview\"><!-- Basic Select --><div class=\"doc-demo__group\"><h3 class=\"doc-demo__group-title\">Basic Usage</h3><div class=\"doc-demo__list doc-demo__list--column\" style=\"max-width: 400px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Select(ui.SelectProp{
			Name: "theme",
			Options: []ui.SelectOption{
				{Label: "System Default", Value: "system"},
				{Label: "Light Mode", Value: "light"},
				{Label: "Dark Mode", Value: "dark"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div><!-- With Placeholder and Preselected --><div class=\"doc-demo__group\"><h3 class=\"doc-demo__group-title\">Placeholder and Pre-selected</h3><div class=\"doc-demo__list doc-demo__list--column\" style=\"max-width: 400px;\"><div class=\"select-demo-row\"><span class=\"text-xs text-muted\">With Placeholder</span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Select(ui.SelectProp{
			Placeholder: "Choose a fruit...",
			Options: []ui.SelectOption{
				{Label: "Apple", Value: "apple"},
				{Label: "Banana", Value: "banana"},
				{Label: "Orange", Value: "orange"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"select-demo-row\"><span class=\"text-xs text-muted\">Pre-selected Value</span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Select(ui.SelectProp{
			Value: "banana",
			Options: []ui.SelectOption{
				{Label: "Apple", Value: "apple"},
				{Label: "Banana", Value: "banana"},
				{Label: "Orange", Value: "orange"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></div></div><!-- States --><div class=\"doc-demo__group\"><h3 class=\"doc-demo__group-title\">States</h3><div class=\"doc-demo__list doc-demo__list--column\" style=\"max-width: 400px;\"><div class=\"select-demo-row\"><span class=\"text-xs text-muted\">Disabled State</span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Select(ui.SelectProp{
			Disabled: true,
			Options: []ui.SelectOption{
				{Label: "Locked Option", Value: "locked"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div class=\"select-demo-row\"><span class=\"text-xs text-muted\">Error State</span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Select(ui.SelectProp{
			Error: true,
			Options: []ui.SelectOption{
				{Label: "Invalid Selection", Value: "invalid"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div></div></div></div></div></section><style type=\"text/css\">\n\t\t.select-demo-row {\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: column;\n\t\t\tgap: 0.25rem;\n\t\t}\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
