// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import ui "github.com/themartian0x48/ui/go"

func getFrameworkOptions() []ui.AutocompleteOption {
	return []ui.AutocompleteOption{
		{Value: "alpine", Label: "Alpine.js"},
		{Value: "angular", Label: "Angular"},
		{Value: "django", Label: "Django"},
		{Value: "ember", Label: "Ember.js"},
		{Value: "express", Label: "Express"},
		{Value: "flutter", Label: "Flutter"},
		{Value: "gin", Label: "Gin"},
		{Value: "htmx", Label: "htmx"},
		{Value: "laravel", Label: "Laravel"},
		{Value: "nextjs", Label: "Next.js"},
		{Value: "nuxt", Label: "Nuxt"},
		{Value: "rails", Label: "Ruby on Rails"},
		{Value: "react", Label: "React"},
		{Value: "solid", Label: "Solid.js"},
		{Value: "spring", Label: "Spring Boot"},
		{Value: "svelte", Label: "Svelte"},
		{Value: "templ", Label: "Templ"},
		{Value: "vue", Label: "Vue.js"},
	}
}

func AutocompleteDemo() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"doc-section\"><header class=\"doc-section__header\"><h1 class=\"doc-section__title\">Autocomplete (Combobox)</h1><p class=\"doc-section__description\">An input field combined with a searchable list of selectable drop-down options.</p></header><div class=\"doc-demo\" style=\"min-height: 400px;\"><!-- Extra height for dropdown overlap bounds --><div class=\"doc-demo__preview\"><!-- Standard Usage --><div class=\"doc-demo__group\"><h3 class=\"doc-demo__group-title\">Basic Usage</h3><div class=\"doc-demo__list\" style=\"max-width: 320px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Autocomplete(ui.AutocompleteProp{
			Id:          "framework",
			Name:        "framework",
			Placeholder: "Search frameworks...",
			Options:     getFrameworkOptions(),
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div><!-- With Initial Value --><div class=\"doc-demo__group\"><h3 class=\"doc-demo__group-title\">Pre-filled Value (Templ)</h3><div class=\"doc-demo__list\" style=\"max-width: 320px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Autocomplete(ui.AutocompleteProp{
			Id:          "framework-prefilled",
			Name:        "framework-prefilled",
			Placeholder: "Search frameworks...",
			Options:     getFrameworkOptions(),
			Value:       "Templ",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div><!-- Disabled & Error states --><div class=\"doc-demo__group\"><h3 class=\"doc-demo__group-title\">States</h3><div class=\"doc-demo__list doc-demo__list--column\" style=\"max-width: 320px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Autocomplete(ui.AutocompleteProp{
			Placeholder: "Disabled autocomplete",
			Options:     getFrameworkOptions(),
			Disabled:    true,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Autocomplete(ui.AutocompleteProp{
			Placeholder: "Error state",
			Options:     getFrameworkOptions(),
			Error:       true,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
