// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "strings"

// SkeletonVariant defines the shape of the skeleton placeholder.
//
// Available variants:
//   - SkeletonText: Single line text placeholder (default)
//   - SkeletonCircular: Round avatar/icon placeholder
//   - SkeletonRectangular: Image/card placeholder
type SkeletonVariant int

const (
	SkeletonText        SkeletonVariant = iota // Single line text placeholder (default)
	SkeletonCircular                           // Round avatar/icon placeholder
	SkeletonRectangular                        // Image/card placeholder
)

// SkeletonSize defines preset sizes for the skeleton.
//
// Size dimensions vary by variant:
//   - Text: SM=12px, MD=16px, LG=24px height
//   - Circular: SM=32px, MD=48px, LG=64px diameter
//   - Rectangular: SM=64px, MD=128px, LG=192px height
type SkeletonSize int

const (
	SkeletonSizeSM SkeletonSize = iota // Small
	SkeletonSizeMD                     // Medium (default)
	SkeletonSizeLG                     // Large
)

// SkeletonProp configures a skeleton loading placeholder component.
//
// Example usage:
//
//	// Basic text skeleton
//	@ui.Skeleton(ui.SkeletonProp{})
//
//	// Avatar placeholder
//	@ui.Skeleton(ui.SkeletonProp{Variant: ui.SkeletonCircular, Size: ui.SkeletonSizeLG})
//
//	// Multiple text lines
//	@ui.Skeleton(ui.SkeletonProp{Lines: 3})
//
//	// Custom dimensions
//	@ui.Skeleton(ui.SkeletonProp{Width: "200px", Height: "100px"})
type SkeletonProp struct {
	Variant    SkeletonVariant  // Shape variant (text, circular, rectangular)
	Size       SkeletonSize     // Size preset (sm, md, lg)
	Width      string           // Custom width (e.g., "200px", "100%")
	Height     string           // Custom height (e.g., "20px")
	Lines      int              // Number of text lines (for Text variant only, max 10)
	Animated   *bool            // Enable shimmer animation (default: true)
	Class      string           // Additional CSS classes
	AriaLabel  string           // Screen reader description (default: "Loading...")
	Attributes templ.Attributes // Additional HTML attributes
}

// skeletonIsAnimated returns whether animation is enabled (defaults to true).
func skeletonIsAnimated(animated *bool) bool {
	if animated == nil {
		return true
	}
	return *animated
}

// skeletonClass generates the CSS class string for a skeleton element.
func skeletonClass(variant SkeletonVariant, size SkeletonSize, animated bool, class string) string {
	var b strings.Builder
	b.Grow(50)

	b.WriteString("skeleton")

	// Variant class
	switch variant {
	case SkeletonCircular:
		b.WriteString(" skeleton--circular")
	case SkeletonRectangular:
		b.WriteString(" skeleton--rectangular")
	default:
		b.WriteString(" skeleton--text")
	}

	// Size class
	switch size {
	case SkeletonSizeSM:
		b.WriteString(" skeleton--sm")
	case SkeletonSizeLG:
		b.WriteString(" skeleton--lg")
	default:
		b.WriteString(" skeleton--md")
	}

	// Animation class
	if animated {
		b.WriteString(" skeleton--animated")
	}

	if class != "" {
		b.WriteString(" ")
		b.WriteString(class)
	}
	return b.String()
}

// skeletonStyle generates inline styles for custom dimensions.
func skeletonStyle(width, height string) string {
	if width == "" && height == "" {
		return ""
	}

	var b strings.Builder
	b.Grow(40)

	if width != "" {
		b.WriteString("width:")
		b.WriteString(width)
		b.WriteString(";")
	}
	if height != "" {
		b.WriteString("height:")
		b.WriteString(height)
		b.WriteString(";")
	}
	return b.String()
}

// Skeleton renders a loading placeholder with optional shimmer animation.
// Use this component to indicate content is loading, improving perceived performance.
//
// Accessibility:
//   - Uses role="status" to announce loading state to screen readers
//   - Includes aria-busy="true" to indicate ongoing operation
//   - Provides visually hidden text for screen reader users
//   - Respects prefers-reduced-motion preference via CSS
func Skeleton(prop SkeletonProp) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		animated := skeletonIsAnimated(prop.Animated)
		lines := prop.Lines
		if lines < 1 {
			lines = 1
		}
		if lines > 10 {
			lines = 10
		}
		ariaLabel := prop.AriaLabel
		if ariaLabel == "" {
			ariaLabel = "Loading..."
		}
		if prop.Variant == SkeletonText && lines > 1 {
			var templ_7745c5c3_Var2 = []any{skeletonGroupClass(prop.Class)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `go/skeleton.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" role=\"status\" aria-busy=\"true\" aria-label=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(ariaLabel)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `go/skeleton.templ`, Line: 157, Col: 25}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, prop.Attributes)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, ">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for i := 0; i < lines; i++ {
				var templ_7745c5c3_Var5 = []any{skeletonClass(prop.Variant, prop.Size, animated, "")}
				templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var5...)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var5).String())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `go/skeleton.templ`, Line: 1, Col: 0}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if i == lines-1 {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, " style=\"width:80%;\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " aria-hidden=\"true\"></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<span class=\"visually-hidden\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(ariaLabel)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `go/skeleton.templ`, Line: 169, Col: 44}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			var templ_7745c5c3_Var8 = []any{skeletonClass(prop.Variant, prop.Size, animated, prop.Class)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var8...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<div class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var8).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `go/skeleton.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "\" style=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues(skeletonStyle(prop.Width, prop.Height))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `go/skeleton.templ`, Line: 174, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\" role=\"status\" aria-busy=\"true\" aria-label=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(ariaLabel)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `go/skeleton.templ`, Line: 177, Col: 25}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, prop.Attributes)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "><span class=\"visually-hidden\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var12 string
			templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(ariaLabel)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `go/skeleton.templ`, Line: 180, Col: 44}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

// skeletonGroupClass generates CSS class for skeleton group container.
func skeletonGroupClass(class string) string {
	if class == "" {
		return "skeleton-group"
	}
	return "skeleton-group " + class
}

var _ = templruntime.GeneratedTemplate
