// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type ToastType string

const (
	ToastInfo    ToastType = "info"
	ToastSuccess ToastType = "success"
	ToastWarning ToastType = "warning"
	ToastError   ToastType = "error"
)

type ToastPosition string

const (
	ToastTopLeft      ToastPosition = "top-left"
	ToastTopCenter    ToastPosition = "top-center"
	ToastTopRight     ToastPosition = "top-right"
	ToastBottomLeft   ToastPosition = "bottom-left"
	ToastBottomCenter ToastPosition = "bottom-center"
	ToastBottomRight  ToastPosition = "bottom-right"
)

type ToastProp struct {
	Id       string
	Type     ToastType
	Title    string
	Message  string
	Class    string
	Position ToastPosition
}

// Toast renders a single toast notification.
// Note: This component is primarily for server-side rendering.
// Client-side toasts are created via JS, but we keep this consistent.
func Toast(prop ToastProp) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{toastClass(prop)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `go/toast.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" role=\"alert\"><div class=\"toast__icon\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		switch prop.Type {
		case ToastSuccess:
			templ_7745c5c3_Err = Icon(IconProp{Icon: IconCheck(), Size: IconSizeMD}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case ToastWarning:
			templ_7745c5c3_Err = Icon(IconProp{Icon: IconWarning(), Size: IconSizeMD}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case ToastError:
			templ_7745c5c3_Err = Icon(IconProp{Icon: IconX(), Size: IconSizeMD}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		default:
			templ_7745c5c3_Err = Icon(IconProp{Icon: IconInfo(), Size: IconSizeMD}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"toast__content\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if prop.Title != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"toast__title\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(prop.Title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `go/toast.templ`, Line: 54, Col: 42}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"toast__message\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(prop.Message)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `go/toast.templ`, Line: 56, Col: 45}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></div><button class=\"toast__close\" onclick=\"this.closest('.toast').remove()\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Icon(IconProp{Icon: IconX(), Size: IconSizeSM}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ToastContainer renders the script and initial markup.
func ToastContainer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = initToastScript().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// Helper functions for classes

func toastClass(prop ToastProp) string {
	base := "toast"
	typeClass := "toast--" + string(prop.Type)

	classes := base + " " + typeClass
	if prop.Class != "" {
		classes += " " + prop.Class
	}
	return classes
}

// Script to initialize global toast function
func initToastScript() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_initToastScript_2f94`,
		Function: `function __templ_initToastScript_2f94(){// Expose Enum values to JS for convenience
	window.ToastPosition = {
		TopLeft: "top-left",
		TopCenter: "top-center",
		TopRight: "top-right",
		BottomLeft: "bottom-left",
		BottomCenter: "bottom-center",
		BottomRight: "bottom-right"
	};

	window.showToast = function(message, type = 'info', title = '', position = 'bottom-right') {
        // Validate position or fallback
        const validPositions = Object.values(window.ToastPosition);
        if (!validPositions.includes(position)) {
            position = window.ToastPosition.BottomRight;
        }

        const containerId = ` + "`" + `toast-container-${position}` + "`" + `;
		let container = document.getElementById(containerId);
		
        if (!container) {
            container = document.createElement('div');
            container.id = containerId;
            container.className = ` + "`" + `toast-container toast-container--${position}` + "`" + `;
            document.body.appendChild(container);
        }

		const toast = document.createElement('div');
		toast.className = ` + "`" + `toast toast--${type}` + "`" + `;
		toast.role = 'alert';
		
        const icons = {
            success: ` + "`" + `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="icon icon--md"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg>` + "`" + `,
            error: ` + "`" + `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="icon icon--md"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>` + "`" + `,
            warning: ` + "`" + `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="icon icon--md"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>` + "`" + `,
            info: ` + "`" + `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="icon icon--md"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>` + "`" + `
        };

		const iconHtml = ` + "`" + `<div class="toast__icon">${icons[type] || icons.info}</div>` + "`" + `;
        const titleHtml = title ? ` + "`" + `<div class="toast__title">${title}</div>` + "`" + ` : '';
        const messageHtml = ` + "`" + `<div class="toast__message">${message}</div>` + "`" + `;
        const closeHtml = ` + "`" + `
            <button class="toast__close" onclick="this.closest('.toast').remove()">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="icon icon--sm">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
                </svg>
            </button>
        ` + "`" + `;

		toast.innerHTML = ` + "`" + `${iconHtml}<div class="toast__content">${titleHtml}${messageHtml}</div>${closeHtml}` + "`" + `;

        if (position.startsWith('top')) {
             container.appendChild(toast);
        } else {
             container.appendChild(toast);
        }

		setTimeout(() => {
			toast.style.opacity = '0';
            if (position.includes('right')) toast.style.transform = 'translateX(100%)';
            else if (position.includes('left')) toast.style.transform = 'translateX(-100%)';
            else if (position.includes('top')) toast.style.transform = 'translateY(-100%)';
            else toast.style.transform = 'translateY(100%)';
            
			setTimeout(() => {
                toast.remove();
                if (container.childNodes.length === 0) {
                    container.remove();
                }
            }, 300);
		}, 3000); 
	};
}`,
		Call:       templ.SafeScript(`__templ_initToastScript_2f94`),
		CallInline: templ.SafeScriptInline(`__templ_initToastScript_2f94`),
	}
}

var _ = templruntime.GeneratedTemplate
