// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import ui "github.com/themartian0x48/ui/go"

func SkeletonDemo() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"doc-section\"><header class=\"doc-section__header\"><h1 class=\"doc-section__title\">Skeleton</h1><p class=\"doc-section__description\">Loading placeholders with shimmer animation to improve perceived performance while content is loading.</p></header><div class=\"doc-demo\"><div class=\"doc-demo__preview\"><!-- Text Variant --><div class=\"doc-demo__group\"><h3 class=\"doc-demo__group-title\">Text Variant</h3><div class=\"doc-demo__list doc-demo__list--column\" style=\"max-width: 400px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
			Variant: ui.SkeletonText,
			Size:    ui.SkeletonSizeSM,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
			Variant: ui.SkeletonText,
			Size:    ui.SkeletonSizeMD,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
			Variant: ui.SkeletonText,
			Size:    ui.SkeletonSizeLG,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div><!-- Text Lines --><div class=\"doc-demo__group\"><h3 class=\"doc-demo__group-title\">Multiple Text Lines</h3><div style=\"max-width: 400px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
			Variant: ui.SkeletonText,
			Lines:   3,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div><!-- Circular Variant --><div class=\"doc-demo__group\"><h3 class=\"doc-demo__group-title\">Circular Variant</h3><div class=\"doc-demo__list\"><div class=\"skeleton-demo__item\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
			Variant: ui.SkeletonCircular,
			Size:    ui.SkeletonSizeSM,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<span class=\"text-xs\">Small</span></div><div class=\"skeleton-demo__item\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
			Variant: ui.SkeletonCircular,
			Size:    ui.SkeletonSizeMD,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<span class=\"text-xs\">Medium</span></div><div class=\"skeleton-demo__item\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
			Variant: ui.SkeletonCircular,
			Size:    ui.SkeletonSizeLG,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<span class=\"text-xs\">Large</span></div></div></div><!-- Rectangular Variant --><div class=\"doc-demo__group\"><h3 class=\"doc-demo__group-title\">Rectangular Variant</h3><div class=\"doc-demo__list doc-demo__list--column\" style=\"max-width: 400px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
			Variant: ui.SkeletonRectangular,
			Size:    ui.SkeletonSizeSM,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
			Variant: ui.SkeletonRectangular,
			Size:    ui.SkeletonSizeMD,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></div><!-- Custom Dimensions --><div class=\"doc-demo__group\"><h3 class=\"doc-demo__group-title\">Custom Dimensions</h3><div class=\"doc-demo__list doc-demo__list--column\" style=\"max-width: 400px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
			Variant: ui.SkeletonText,
			Width:   "60%",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
			Variant: ui.SkeletonRectangular,
			Width:   "200px",
			Height:  "100px",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
			Variant: ui.SkeletonCircular,
			Width:   "80px",
			Height:  "80px",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div></div><!-- Card Loading Example --><div class=\"doc-demo__group\"><h3 class=\"doc-demo__group-title\">Card Loading Example</h3><div style=\"max-width: 320px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div class=\"skeleton-demo__card\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
				Variant:   ui.SkeletonRectangular,
				Height:    "160px",
				AriaLabel: "Loading image",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<div class=\"skeleton-demo__card-content\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
				Variant:   ui.SkeletonText,
				Size:      ui.SkeletonSizeLG,
				Width:     "70%",
				AriaLabel: "Loading title",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
				Variant:   ui.SkeletonText,
				Lines:     2,
				AriaLabel: "Loading description",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = ui.Card(ui.CardProp{}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div></div><!-- Profile Loading Example --><div class=\"doc-demo__group\"><h3 class=\"doc-demo__group-title\">Profile Loading Example</h3><div class=\"skeleton-demo__profile\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
			Variant:   ui.SkeletonCircular,
			Size:      ui.SkeletonSizeLG,
			AriaLabel: "Loading avatar",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<div class=\"skeleton-demo__profile-info\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
			Variant:   ui.SkeletonText,
			Size:      ui.SkeletonSizeMD,
			Width:     "150px",
			AriaLabel: "Loading name",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
			Variant:   ui.SkeletonText,
			Size:      ui.SkeletonSizeSM,
			Width:     "100px",
			AriaLabel: "Loading role",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</div></div></div><!-- List Loading Example --><div class=\"doc-demo__group\"><h3 class=\"doc-demo__group-title\">List Loading Example</h3><div class=\"skeleton-demo__list\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for i := 0; i < 3; i++ {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<div class=\"skeleton-demo__list-item\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
				Variant: ui.SkeletonCircular,
				Size:    ui.SkeletonSizeMD,
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "<div class=\"skeleton-demo__list-content\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
				Variant: ui.SkeletonText,
				Size:    ui.SkeletonSizeMD,
				Width:   "70%",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
				Variant: ui.SkeletonText,
				Size:    ui.SkeletonSizeSM,
				Width:   "50%",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "</div></div><!-- Without Animation --><div class=\"doc-demo__group\"><h3 class=\"doc-demo__group-title\">Without Animation</h3><p class=\"skeleton-demo__text\">Animation can be disabled by setting Animated to false.</p><div style=\"max-width: 400px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonProp{
			Variant:  ui.SkeletonText,
			Lines:    2,
			Animated: boolPtr(false),
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "</div></div></div></div></section><style type=\"text/css\">\n\t\t.skeleton-demo__item {\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: column;\n\t\t\talign-items: center;\n\t\t\tgap: var(--spacing-3);\n\t\t\tcolor: var(--color-text-muted);\n\t\t}\n\t\t.skeleton-demo__text {\n\t\t\tmargin-bottom: var(--spacing-4);\n\t\t\tcolor: var(--color-text-muted);\n\t\t\tfont-size: var(--font-size-sm);\n\t\t}\n\t\t.skeleton-demo__card {\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: column;\n\t\t\tgap: var(--spacing-4);\n\t\t\tmargin: calc(-1 * var(--spacing-4));\n\t\t}\n\t\t.skeleton-demo__card-content {\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: column;\n\t\t\tgap: var(--spacing-3);\n\t\t\tpadding: 0 var(--spacing-4) var(--spacing-4);\n\t\t}\n\t\t.skeleton-demo__profile {\n\t\t\tdisplay: flex;\n\t\t\talign-items: center;\n\t\t\tgap: var(--spacing-4);\n\t\t\tpadding: var(--spacing-4);\n\t\t\tbackground: var(--color-bg-secondary);\n\t\t\tborder-radius: var(--radius-md);\n\t\t\tborder: var(--border-width-thin) solid var(--color-border);\n\t\t}\n\t\t.skeleton-demo__profile-info {\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: column;\n\t\t\tgap: var(--spacing-2);\n\t\t}\n\t\t.skeleton-demo__list {\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: column;\n\t\t\tgap: var(--spacing-4);\n\t\t\tpadding: var(--spacing-4);\n\t\t\tbackground: var(--color-bg-secondary);\n\t\t\tborder-radius: var(--radius-md);\n\t\t\tborder: var(--border-width-thin) solid var(--color-border);\n\t\t\tmax-width: 400px;\n\t\t}\n\t\t.skeleton-demo__list-item {\n\t\t\tdisplay: flex;\n\t\t\talign-items: center;\n\t\t\tgap: var(--spacing-3);\n\t\t}\n\t\t.skeleton-demo__list-content {\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: column;\n\t\t\tgap: var(--spacing-2);\n\t\t\tflex: 1;\n\t\t}\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
